version: '3.1'
volumes:
  db_data:

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: 'alkemist_test'
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '1234:5432'
